name: Javadoc Automático en Stable
on:
  push:
    branches:
      - stable  

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generar HTML de Javadoc
        run: javadoc -d ./docs-dist -sourcepath src/main/java -subpackages com.tt1.test
      - name: Preparar subida a GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs-dist
      - name: Publicar en la Web (GitHub Pages)
        id: deployment
        uses: actions/deploy-pages@v4
